### ISSUE TITLE
Will this work for cats?

### ISSUE THREAD

**Issue by franz101** [ZhenglinZhou/HeadStudio#3]
I assume not unless I get their facial marks

**Comment by ZhenglinZhou** [comment]
Hi @franz101, thanks for your interest!

We evaluate HeadStudio using prompts with animal character, such as: a head of a metal sculpture of a lion. As shown below, HeadStudio successfully created the animal character. However, the animation result did not match that of human-like characters due to constraints from the FLAME model.

In conclusion, the animal prior model, such as [SMAL](https://arxiv.org/pdf/1611.07700.pdf), is recommended to replace the FLAME model in HeadStudio for improved animal (e.g., cats) avatar generation.

![a_head_of_a_metal_sculpture_of_a_lion](https://github.com/ZhenglinZhou/HeadStudio/assets/42434623/6dfc7841-6f03-40a1-bd40-694309ccbfa2)

We hope this answers your questions. If you have any other questions, feel free to leave a comment.
